# -*- coding: utf-8 -*-
"""mini_project_surya teja.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z6iFpJdIjyBwtD8RDLGTIlbd6leEsRCr
"""

# student_progress.py
print("-----------------------------------------")
print("   STUDENT PROGRESS TRACKER SYSTEM")
print("-----------------------------------------")

# basic student details
student_name = input("Name: ")
student_class = input("Class: ")
roll_no = input("Roll No: ")6
# we'll keep the latest report data in these
marks = []
total = 0
avg = 0
grade = ""
result = ""

# menu loop to mimic do-while
while True:
    try:
        n = int(input("\nHow many subjects do you want to enter? "))
    except ValueError:
        print("Please enter a number.")
        continue

    marks = []
    total = 0

    for i in range(n):
        while True:
            try:
                m = int(input(f"Enter marks for subject {i+1}: "))
                if m < 0 or m > 100:
                    print("Enter marks between 0 and 100.")
                    continue
                break
            except ValueError:
                print("Please enter a valid integer.")
        marks.append(m)
        total += m

    # average
    if n > 0:
        avg = total / n
    else:
        avg = 0

    # grade by average
    if avg >= 90:
        grade = "A"
    elif avg >= 75:
        grade = "B"
    elif avg >= 50:
        grade = "C"
    elif avg >= 35:
        grade = "D"
    else:
        grade = "Fail"

    # pass/fail: fail if any subject < 28
    if marks and min(marks) < 20:
        result = "FAIL"
    else:
        result = "PASS"

    # print report (simple formatting)
    print("\n-----------------------------------------")
    print("         STUDENT PROGRESS REPORT")
    print("-----------------------------------------")
    print(f"Name        : {student_name}")
    print(f"Class       : {student_class}")
    print(f"Roll No     : {roll_no}")
    print(f"Total Marks : {total}")
    print(f"Average     : {avg:.2f}")
    print(f"Grade       : {grade}")
    print(f"Result      : {result}")
    print("-----------------------------------------")

    # menu
    print("\nWhat do you want next?")
    print("1. Enter marks again")
    print("2. View report again")
    print("3. Exit")

    choice = input("Choice: ").strip()

    if choice == "1":
        # loop repeats to enter marks again
        continue
    elif choice == "2":
        # reprint report quickly
        print("\n--- Reprinting report ---")
        print(f"{student_name} | Class: {student_class} | Roll: {roll_no}")
        print(f"Total {total} | Avg {avg:.2f} | Grade {grade} | {result}")
        # after reprint show menu again
        continue
    elif choice == "3":
        print("Exiting. Good luck!")
        break
    else:
        print("Invalid choice, returning to menu.")
        # loop continues